// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivdtefqljskdxdkewlal.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2ZHRlZnFsanNrZHhka2V3bGFsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYwMjg4MTEsImV4cCI6MjA2MTYwNDgxMX0.Gmh1ShKEqEi2q0mFy-4Y_2foi7f4BewBPda5n3fxbaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);